// Generated by https://quicktype.io

export interface NewsResponse {
  id: number;
  title: string;
  contentList: string[];
  timestamp: number;
  utime: string;
}

// Generated by https://quicktype.io

export interface KataOptions {
  value: string;
  label: string;
  id?: number;
  children: KataOptions[];
  isRemote?: number;
}

export interface KataOption {
  title: string;
  content: string;
}

export interface HistoriesResponse {
  id: number;
  title: string;
  description: string;
  date: string;
}
